{{- if .Values.ConfigMap }}

{{- $app_name := default (include "demo.name" .) .Values.ConfigMap.name }}
{{- $release_namespace := .Release.namespace }}
{{- $labels := include "demo.labels" . }}

{{- with .Values.ConfigMap }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $app_name }}
  namespace: {{ $release_namespace }}
  
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
{{ $labels | indent 4 }}
  {{- with .labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}

{{- with .data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}

{{- with .binaryData }}
binaryData:
  {{- toYaml . | nindent 2 }}
{{- end }}

{{- end }}
{{- end }}