{{- if .Values.Deployment }}

{{- $app_name := default (include "demo.name" .) .Values.Deployment.name }}
{{- $release_namespace := .Release.namespace }}
{{- $release_name := .Release.name }}
{{- $labels := include "demo.labels" . }}

{{- with .Values.Deployment }}

apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ $app_name }}
  namespace: {{ $release_namespace }}
  
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
{{ $labels | indent 4 }}
  {{- with .labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  replicas: {{ required "No. of replicas are required" .replicas }}
  minReadySeconds: {{ default nil .minReadySeconds | quote }}
  progressDeadlineSeconds: {{ default nil .progressDeadlineSeconds | quote }}
  paused: {{ default nil .paused | quote }}
  revisionHistoryLimit: {{ default 10 .revisionHistoryLimit }}
  
  {{- with .strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $app_name }}
      app.kubernetes.io/instance: {{ $release_name }}
      {{- with .labels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}

  {{- with .template }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $app_name }}
        app.kubernetes.io/instance: {{ $release_name }}
        {{- with .labels }}
          {{- toYaml . | nindent 10 }}
        {{- end }}

    spec:
    {{- include "pod" . | nindent 6 }}
            
  {{- end }}
{{- end }}
{{- end }}