{{- if .Values.Ingress }}

{{- $app_name := default (include "demo.name" .) .Values.Ingress.name }}
{{- $release_namespace := .Release.namespace }}
{{- $labels := include "demo.labels" . }}

{{- with .Values.Ingress }}

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $app_name }}
  namespace: {{ $release_namespace }}

  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
{{ $labels | indent 4 }}
  {{- with .labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  
  {{- with .backend }}
  backend:
    serviceName: {{ default nil .serviceName }}
    servicePort: {{ default nil .servicePort }}
  {{- end }}

  {{- with .rules }}
  rules: 
    {{- toYaml . | nindent 4 }}
  {{- end }}
  
  {{- with .tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}

{{- end }}
{{- end }}