{{- if .Values.Job }}

{{- $app_name := default (include "demo.name" .) .Values.Job.name }}
{{- $release_namespace := .Release.namespace }}
{{- $release_name := .Release.name }}
{{- $labels := include "demo.labels" . }}

{{- with .Values.Job }}

apiVersion: batch/v1
kind: Job

metadata:
  name: {{ $app_name }}
  namespace: {{ $release_namespace }}

  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
{{ $labels | indent 4 }}
  {{- with .labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  backoffLimit: {{ default 6 .backoffLimit }}
  activeDeadlineSeconds: {{ default nil .activeDeadlineSeconds | quote }}
  completions: {{ default nil .completions | quote }}
  manualSelector: {{ default nil .manualSelector | quote }}
  parallelism: {{ default nil .parallelism | quote }}
  ttlSecondsAfterFinished: {{ default nil .ttlSecondsAfterFinished | quote }}

  {{- with .template }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $app_name }}
        app.kubernetes.io/instance: {{ $release_name }}
        {{- with .labels }}
          {{- toYaml . | nindent 10 }}
        {{- end }}

    spec:
    {{- include "pod" . | nindent 6 }}
  {{- end }}
{{- end }}
{{- end }}

