{{- if .Values.PersistentVolumeClaim }}

{{- $release_namespace := .Release.namespace }}
{{- $labels := include "demo.labels" . }}

{{- $app_name := include "demo.name" . }}

{{- range $pvc := .Values.PersistentVolumeClaim }}
{{- with $pvc }}

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $app_name }}
  namespace: {{ $release_namespace }}
  
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
{{ $labels | indent 4 }}
  {{- with .labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  
  {{- with .selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  
  storageClassName: {{ default nil .storageClassName | quote }}
  volumeName: {{ default nil .volumeName | quote }}
  volumeMode: {{ default nil .volumeMode | quote }}
  
  resources:
    requests:
      storage: {{ required "Storage size is required" .resources.requests.storage }}

  {{- with .accessModes }}
  accessModes:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .dataSource }}
  dataSource:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}