{{- if .Values.Secret }}

{{- $app_name := default (include "demo.name" .) .Values.Secret.name }}
{{- $release_namespace := .Release.namespace }}
{{- $release_name := .Release.name }}
{{- $labels := include "demo.labels" . }}

{{- with .Values.Secret }}

apiVersion: v1
kind: Secret

metadata:
  name: {{ $app_name }}
  namespace: {{ $release_namespace }}
  
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
{{ $labels | indent 4 }}
  {{- with .labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}

type: {{ .type }}

{{- with .data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}

{{- with .stringData }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}

{{- end }}
{{- end }}
