{{- if .Values.StatefulSet }}

{{- $app_name := default (include "demo.name" .) .Values.StatefulSet.name }}
{{- $release_namespace := .Release.namespace }}
{{- $release_name := .Release.name }}
{{- $labels := include "demo.labels" . }}

{{- with .Values.StatefulSet }}

apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: {{ $app_name }}
  namespace: {{ $release_namespace }}
  
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
{{ $labels | indent 4 }}
  {{- with .labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  replicas: {{ default 1 .replicas }}
  podManagementPolicy: {{ .podManagementPolicy | default "OrderedReady" | quote }}
  revisionHistoryLimit: {{ default 10 .revisionHistoryLimit }}
  serviceName: {{ required "serviceName is required" .serviceName }}
  
  {{- with .updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $app_name }}
      app.kubernetes.io/instance: {{ $release_name }}
      {{- with .labels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}

  {{- with .template }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $app_name }}
        app.kubernetes.io/instance: {{ $release_name }}
        {{- with .labels }}
          {{- toYaml . | nindent 10 }}
        {{- end }}

    spec:
    {{- include "pod" . | nindent 6 }}
  
  volumeClaimTemplates:
  {{- include "volumeClaimTemplate" .volumeClaimTemplates | nindent 4 }}
            
  {{- end }}
{{- end }}
{{- end }}